export const team = [
  {
    id: 1,
    image: "/images/our-agents/omnia-hansy.png",
    alt: "Omneya Rouby",
    name: "Omneya Rouby",
    title: "General Manager",
  },
  {
    id: 2,
    image: "/images/our-agents/nada-waly.png",
    alt: "Nada Waly",
    name: "Nada Waly",
    title: "Sales Director",
  },
  {
    id: 3,
    image: "/images/our-agents/mahmoud-salama.png",
    alt: "Mahmoud Salama",
    name: "Mahmoud Salama",
    title: "Sales Director",
  },
  {
    id: 4,
    image: "/images/our-agents/shady-soliman.png",
    alt: "Shady Soliman",
    name: "Shady Soliman",
    title: "Sales Director",
  },
  {
    id: 5,
    image: "/images/our-agents/heba-ahmed.png",
    alt: "Heba Ahmed",
    name: "Heba Ahmed",
    title: "Sales Director",
  },
  {
    id: 6,
    image: "/images/our-agents/ahmed-sabry.png",
    alt: "Ahmed Sabry",
    name: "Ahmed Sabry",
    title: "Sales Manager",
  },
  {
    id: 7,
    image: "/images/our-agents/mohamed-essa.png",
    alt: "Mohamed Eissa",
    name: "Mohamed Eissa",
    title: "Sales Manager",
  },
  {
    id: 8,
    image: "/images/our-agents/mahmoud-kamel.png",
    alt: "Mahmoud Kamel",
    name: "Mahmoud Kamel",
    title: "Sales Manager",
  },
  {
    id: 9,
    image: "/images/our-agents/mohamed-said.png",
    alt: "Mohamed Said",
    name: "Mohamed Said",
    title: "Sales Manager",
  },
  {
    id: 10,
    image: "/images/our-agents/shehab-ramzy.png",
    alt: "Shehab Ramzy",
    name: "Shehab Ramzy",
    title: "Sales Manager",
  },
  {
    id: 11,
    image: "/images/our-agents/dina-elgarem.png",
    alt: "Dina El-Garem",
    name: "Dina El-Garem",
    title: "Operation Manager",
  },
];
